services:
  - type: web
    name: 450mtforum
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: 450mtforum_db
          property: connectionString
    disk:
      name: logs
      mountPath: /opt/render/project/src/logs
      sizeGB: 1

  - type: postgres
    name: 450mtforum_db
    ipAllowList: []
    plan: free 